In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [3]:
message=pd.read_csv('/content/spam.csv',encoding='ISO-8859-1')

In [ ]:
message=message[['v1','v2']]
message.head()

In [8]:
message.columns=['label','message']

In [11]:
from nltk.corpus import stopwords
nltk.download("stopwords")
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
corpus

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=4000)
X = cv.fit_transform(corpus).toarray()
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=4000)
X = cv.fit_transform(corpus).toarray()

y=pd.get_dummies(message['label'])
y=y.iloc[:,1].values

In [ ]:
message['label'].value_counts().plot(kind='bar')

In [18]:
X,y

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([0, 0, 1, ..., 0, 0, 0], dtype=uint8))

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)


In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB

In [21]:
model=RandomForestClassifier()
model.fit(X_train,y_train)
pred=model.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [24]:
print(confusion_matrix(y_test,pred))

[[965   0]
 [ 26 124]]


In [26]:
print(accuracy_score(y_test,pred))

0.9766816143497757


In [27]:
model_2=DecisionTreeClassifier()
model_2.fit(X_train,y_train)
pred2=model_2.predict(X_test)

In [28]:
print(confusion_matrix(y_test,pred2)),print(accuracy_score(y_test,pred2))

[[958   7]
 [ 23 127]]
0.9730941704035875


(None, None)

In [29]:
model_3=MultinomialNB()
model_3.fit(X_train,y_train)
pred3=model_3.predict(X_test)

In [30]:
print(confusion_matrix(y_test,pred3)),print(accuracy_score(y_test,pred3))

[[955  10]
 [ 10 140]]
0.9820627802690582


(None, None)